name: Push
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
        - run: echo "This job was automatically triggered by a ${{ github.event_name }} event."
